import Head from "next/head";
import { Center } from "@mantine/core";

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Center maw={400} h={100} mx="auto">
				Cet
			</Center>
		</>
	);
}
